### ISSUE TITLE
database

### ISSUE THREAD

**Issue by mizzcode** [galihap76/crud-java-sederhana-cli#1]
>>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
            con = DriverManager.getConnection(url, user, pass);
            stm = con.createStatement();

kie nggo lib/object/database apa gal? ana docs e?

**Comment by galihap76** [comment]
> >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
>             con = DriverManager.getConnection(url, user, pass);
>             stm = con.createStatement();
> 
> kie nggo lib/object/database apa gal? ana docs e?

Nggo library bah kue.

**Comment by galihap76** [comment]
> >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
>             con = DriverManager.getConnection(url, user, pass);
>             stm = con.createStatement();
> 
> kie nggo lib/object/database apa gal? ana docs e?

Nggo install maring situs resmi [mysql](https://dev.mysql.com/downloads/connector/j/).

**Comment by galihap76** [comment]
> >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
>             con = DriverManager.getConnection(url, user, pass);
>             stm = con.createStatement();
> 
> kie nggo lib/object/database apa gal? ana docs e?

Yen wis install tinggal set ning environment path cmd windows. Tutorial [youtube](https://youtu.be/FJPTcFvGPG4?si=h2zJmxdOb2jnZ0Dl).

**Comment by mizzcode** [comment]
> > >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
> >             con = DriverManager.getConnection(url, user, pass);
> >             stm = con.createStatement();
> > 
> > kie nggo lib/object/database apa gal? ana docs e?
> 
> Nggo install maring dokumentasi situs resmi [mysql](https://dev.mysql.com/downloads/connector/j/). 

Install mysql?

**Comment by galihap76** [comment]
> > > >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
> > >             con = DriverManager.getConnection(url, user, pass);
> > >             stm = con.createStatement();
> > > 
> > > kie nggo lib/object/database apa gal? ana docs e?
> > 
> > Nggo install maring dokumentasi situs resmi [mysql](https://dev.mysql.com/downloads/connector/j/). 
> 
> Install mysql?

Iya install library java connector mysql.

**Comment by mizzcode** [comment]
> > > > >>Class.forName("com.mysql.cj.jdbc.Driver"); // Menggunakan driver yang benar
> > > >             con = DriverManager.getConnection(url, user, pass);
> > > >             stm = con.createStatement();
> > > > 
> > > > kie nggo lib/object/database apa gal? ana docs e?
> > > 
> > > Nggo install maring dokumentasi situs resmi [mysql](https://dev.mysql.com/downloads/connector/j/). 
> > 
> > Install mysql?
> 
> Iya install library java connector mysql. 

Ok suwun gal
